# Troubleshooting {#troubleshooting .unnumbered}

-   If you're having difficulty launcging an RStudio session from your reserved container, go to [status.oit.duke.edu](https://status.oit.duke.edu/) and scroll down to **Teaching and Learning Tools**.
    Under this heading you'll find an entry called *Container Manager (CMGR Coursework Containers)*.

    -   If the status shows something other than `Operational`, this means there is a known incident with the containers. Use your course discussion forum to report the issue.
    -   If the status shows `Operational`, this means the system is expected to be working. Check your internet connection, try opening the container in a different web browser, and if need be, restart your computer to ensure a fresh new connection. If the issue still persists, try [restarting the cotainer](Restart_Docker_Container.pdf). Lastly, if the issue is still unresolved, file ticket by filling out the Qualtrics form [here](https://duke.qualtrics.com/jfe/form/SV_6s3DOsiCIzNya9w). If there's an imminent deadline, also consider posting on the course discussion forum.
